version: "3.9"

services:
    mongodb:
        image: puru80/mongo:v-1.0
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - type: volume
              source: mydata
              target: /data
              volume:
                  nocopy: true
        environment:
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
    mongo-express:
        image: puru80/mongo-express:v-1.0
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_MONGODB_SERVER=mongodb

volumes: 
    mydata: 

networks:
    default:
        name: mongo_network
    